import { Plus } from 'lucide-react'
import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router'
import { ticketsApi, type TicketPage } from '../api/ticketsApi'
import { TicketFilters } from '../components/tickets/TicketFilters'
import { TicketSummaryCards } from '../components/tickets/TicketSummaryCards'
import { TicketTable } from '../components/tickets/TicketTable'
import { Button } from '../components/ui/Button'
import { Pagination } from '../components/ui/Pagination'

export default function MyTickets(){const navigate=useNavigate();const[data,setData]=useState<TicketPage|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[search,setSearch]=useState('');const[status,setStatus]=useState('');const[category,setCategory]=useState('');const[page,setPage]=useState(1);useEffect(()=>setPage(1),[search,status,category]);useEffect(()=>{const timer=setTimeout(()=>{setLoading(true);setError('');ticketsApi.my({search,status:status.replaceAll(' ',''),category,page:String(page),pageSize:'20'}).then(setData).catch(reason=>setError(reason instanceof Error?reason.message:'Unable to load tickets.')).finally(()=>setLoading(false))},250);return()=>clearTimeout(timer)},[search,status,category,page]);const tickets=data?.items??[];return <div className="page"><div className="page-heading"><div><span className="eyebrow">Employee workspace</span><h1>My Tickets</h1><p>View and track all the support tickets you’ve created.</p></div><Button onClick={()=>navigate('/tickets/new')}><Plus size={18}/>Create New Ticket</Button></div><TicketSummaryCards counts={{all:data?.totalCount??0,open:data?.open??0,inProgress:data?.inProgress??0,resolved:data?.resolved??0}}/><section className="panel"><div className="section-heading"><div><h2>Your requests</h2><p>Search, filter, and open a ticket for its latest activity.</p></div></div><TicketFilters {...{search,setSearch,status,setStatus,category,setCategory}}/>{error?<div className="empty-state"><strong>Unable to load tickets</strong><p>{error}</p><Button onClick={()=>setPage(current=>current)}>Retry</Button></div>:loading?<div className="empty-state" role="status">Loading tickets…</div>:<TicketTable tickets={tickets}/>}<p className="result-count">Showing {tickets.length} of {data?.totalCount??0} tickets</p><Pagination page={data?.page??page} totalPages={data?.totalPages??0} onChange={setPage}/></section></div>}
