import { Bell, Mail, UserRound } from 'lucide-react'
import { useState } from 'react'
import { useSession } from '../context/SessionContext'

export default function Settings() {
  const { currentUser } = useSession()
  const [emailUpdates, setEmailUpdates] = useState(true)
  const [assignmentUpdates, setAssignmentUpdates] = useState(true)
  if (!currentUser) return null
  const description = currentUser.role === 'Employee' ? 'Manage your profile and personal support preferences.' : currentUser.role === 'Support Agent' ? 'Manage your profile and personal workspace preferences.' : 'Review your profile and personal viewing preferences.'
  return <div className="page"><div className="page-heading"><div><span className="eyebrow">Personal preferences</span><h1>My Settings</h1><p>{description}</p></div></div><div className="settings-layout"><nav className="settings-tabs" aria-label="Settings sections"><button className="active">Profile</button><button>Notifications</button></nav><div><section className="panel settings-list"><div className="section-heading"><div><h2>Profile</h2><p>Your current mock identity in this prototype.</p></div></div><div className="setting-row personal-setting"><span className="setting-icon"><UserRound/></span><span><strong>{currentUser.name}</strong><small>Display name</small></span><b>{currentUser.initials}</b></div><div className="setting-row personal-setting"><span className="setting-icon"><Mail/></span><span><strong>{currentUser.name.toLowerCase().replace(' ', '.')}@company.com</strong><small>Company email</small></span><b>{currentUser.role}</b></div></section><div className="notice settings-notice"><Bell/><div><strong>Prototype notification preferences</strong><p>Notification events, delivery channels, and defaults are illustrative assumptions and require stakeholder confirmation.</p></div></div><section className="panel preference"><div><h2>Email ticket updates</h2><p>Preview email alerts for changes to tickets relevant to you.</p></div><button role="switch" aria-label="Email ticket updates" aria-checked={emailUpdates} className={`toggle ${emailUpdates ? 'on' : ''}`} onClick={() => setEmailUpdates(!emailUpdates)}><span/></button></section><section className="panel preference"><div><h2>Assignment updates</h2><p>Preview alerts when ticket ownership changes.</p></div><button role="switch" aria-label="Assignment updates" aria-checked={assignmentUpdates} className={`toggle ${assignmentUpdates ? 'on' : ''}`} onClick={() => setAssignmentUpdates(!assignmentUpdates)}><span/></button></section></div></div></div>
}
