import { CircleDot, Clock3, UserRoundX } from 'lucide-react'
import { useEffect, useState } from 'react'
import { useLocation } from 'react-router'
import { ticketsApi, type TicketPage } from '../api/ticketsApi'
import { MetricCard } from '../components/dashboard/MetricCard'
import { TicketFilters } from '../components/tickets/TicketFilters'
import { TicketTable } from '../components/tickets/TicketTable'
import { Pagination } from '../components/ui/Pagination'
import type { User } from '../types/user'

export default function SupportQueue(){const allTickets=useLocation().pathname.endsWith('/all');const[data,setData]=useState<TicketPage|null>(null);const[agents,setAgents]=useState<User[]>([]);const[search,setSearch]=useState('');const[status,setStatus]=useState('');const[category,setCategory]=useState('');const[owner,setOwner]=useState('');const[page,setPage]=useState(1);const[loading,setLoading]=useState(true);const[error,setError]=useState('');useEffect(()=>{void ticketsApi.agents().then(setAgents).catch(()=>setAgents([]))},[]);useEffect(()=>setPage(1),[search,status,category,owner,allTickets]);useEffect(()=>{const timer=setTimeout(()=>{setLoading(true);setError('');const filters={search,status:status.replaceAll(' ',''),category,ownerId:owner,page:String(page),pageSize:'20'};const request=allTickets?ticketsApi.all(filters):ticketsApi.queue(filters);request.then(setData).catch(reason=>setError(reason instanceof Error?reason.message:'Unable to load tickets.')).finally(()=>setLoading(false))},250);return()=>clearTimeout(timer)},[search,status,category,owner,allTickets,page]);const tickets=data?.items??[];return <div className="page"><div className="page-heading"><div><span className="eyebrow">Support workspace</span><h1>{allTickets?'All Tickets':'Support Queue'}</h1><p>{allTickets?'View all support requests across the workspace.':'Review, assign, and manage incoming support requests.'}</p></div></div><div className="metrics three"><MetricCard label="Unassigned" value={data?.unassigned??0} icon={UserRoundX} tone="amber"/><MetricCard label="Open" value={data?.open??0} icon={CircleDot}/><MetricCard label="In Progress" value={data?.inProgress??0} icon={Clock3} tone="purple"/></div><section className="panel"><div className="section-heading"><div><h2>{allTickets?'Ticket directory':'Incoming requests'}</h2><p>{data?.totalCount??0} tickets match the current view.</p></div></div><TicketFilters {...{search,setSearch,status,setStatus,category,setCategory,owner,setOwner}} showOwner ownerOptions={agents.map(agent=>({value:agent.id,label:agent.name}))}/>{error?<div className="empty-state"><strong>Unable to load queue</strong><p>{error}</p></div>:loading?<div className="empty-state" role="status">Loading tickets…</div>:<TicketTable tickets={tickets} queue/>}<Pagination page={data?.page??page} totalPages={data?.totalPages??0} onChange={setPage}/></section></div>}
