using System.ComponentModel.DataAnnotations;
using HelpDeskLite.Api.Domain;
namespace HelpDeskLite.Api.Contracts;
public sealed record LoginRequest([Required,EmailAddress,MaxLength(256)]string Email,[Required,MaxLength(200)]string Password,bool RememberMe=false);
public sealed record UserDto(string Id,string Name,string Email,string Role,string Initials);
public sealed record CreateTicketRequest([Required,MaxLength(200)]string Title,[Required,MaxLength(80)]string Category,[Required,MaxLength(5000)]string Description);
public sealed record ChangeAssigneeRequest([MaxLength(450)]string? UserId);
public sealed record ChangeStatusRequest([EnumDataType(typeof(TicketStatus))]TicketStatus Status);
public sealed record CreateCommentRequest([Required,MaxLength(4000)]string Body);
public sealed record CommentDto(int Id,string Author,string Body,DateTimeOffset CreatedAt);
public sealed record HistoryDto(int Id,string Title,string Detail,DateTimeOffset CreatedAt);
public sealed record TicketDto(int Id,string TicketNumber,string Title,string Description,string Category,TicketStatus Status,TicketPriority Priority,string CreatedBy,string? AssignedTo,string? AssignedToUserId,DateTimeOffset CreatedAt,DateTimeOffset UpdatedAt,DateTimeOffset? ResolvedAt,IReadOnlyList<CommentDto> Comments,IReadOnlyList<HistoryDto> History);
public sealed record TicketQuery([MaxLength(200)]string? Search,[EnumDataType(typeof(TicketStatus))]TicketStatus? Status,[MaxLength(80)]string? Category,[MaxLength(450)]string? OwnerId,[Range(1,int.MaxValue)]int Page=1,[Range(1,100)]int PageSize=20);
public sealed record TicketPageDto(IReadOnlyList<TicketDto> Items,int Page,int PageSize,int TotalCount,int TotalPages,int Open,int InProgress,int InReview,int Resolved,int Unassigned);
public sealed record WorkloadDto(string UserId,string Name,int ActiveTickets);
public sealed record ManagerSummaryDto(int Open,int Unassigned,int InProgress,int Resolved,IReadOnlyList<WorkloadDto> Workload,IReadOnlyList<TicketDto> RecentTickets,IReadOnlyList<TicketDto> NeedsAttention);
public sealed record AttachmentDto(int Id,string OriginalFileName,string ContentType,long SizeBytes,string UploadedBy,DateTimeOffset CreatedAt);
