using System.Net.Http.Headers;using System.Security.Claims;using System.Text.Encodings.Web;using HelpDeskLite.Api.Data;using HelpDeskLite.Api.Domain;using HelpDeskLite.Api.Services;using Microsoft.AspNetCore.Authentication;using Microsoft.AspNetCore.Hosting;using Microsoft.AspNetCore.Identity;using Microsoft.AspNetCore.Mvc.Testing;using Microsoft.EntityFrameworkCore;using Microsoft.EntityFrameworkCore.Infrastructure;using Microsoft.EntityFrameworkCore.Storage;using Microsoft.Extensions.DependencyInjection;using Microsoft.Extensions.DependencyInjection.Extensions;using Microsoft.Extensions.Logging;using Microsoft.Extensions.Options;
namespace HelpDeskLite.Api.Tests;
public sealed class ApiFactory:WebApplicationFactory<Program>{
    private bool seeded;private readonly object seedLock=new();private readonly InMemoryDatabaseRoot databaseRoot=new();public string AttachmentRoot{get;}=Path.Combine(Path.GetTempPath(),$"helpdesk-attachments-{Guid.NewGuid():N}");
    public const string EmployeeId="employee-1",OtherEmployeeId="employee-2",AgentId="agent-1",ManagerId="manager-1";
    protected override void ConfigureWebHost(IWebHostBuilder builder){builder.UseEnvironment("Testing");builder.ConfigureServices(services=>{services.RemoveAll(typeof(DbContextOptions<ApplicationDbContext>));services.RemoveAll(typeof(IDbContextOptionsConfiguration<ApplicationDbContext>));services.AddDbContext<ApplicationDbContext>(options=>options.UseInMemoryDatabase("helpdesk-tests",databaseRoot));services.Configure<AttachmentStorageOptions>(options=>{options.RootPath=AttachmentRoot;options.MaxFileSizeBytes=5*1024*1024;options.MaxFilesPerTicket=3;});services.AddAuthentication(options=>{options.DefaultAuthenticateScheme=TestAuthHandler.SchemeName;options.DefaultChallengeScheme=TestAuthHandler.SchemeName;options.DefaultForbidScheme=TestAuthHandler.SchemeName;}).AddScheme<AuthenticationSchemeOptions,TestAuthHandler>(TestAuthHandler.SchemeName,_=>{});});}
    public HttpClient ClientFor(string id,string role){EnsureSeeded();var client=CreateClient();client.DefaultRequestHeaders.Add("X-Test-User",id);client.DefaultRequestHeaders.Add("X-Test-Role",role);client.DefaultRequestHeaders.Authorization=new AuthenticationHeaderValue(TestAuthHandler.SchemeName);return client;}
    private static void Seed(ApplicationDbContext db){db.Roles.Add(new IdentityRole{Id="role-agent",Name=AppRoles.SupportAgent,NormalizedName=AppRoles.SupportAgent.ToUpperInvariant()});db.Users.AddRange(new ApplicationUser{Id=EmployeeId,UserName="omar@test",Email="omar@test",DisplayName="Omar Mohamed"},new ApplicationUser{Id=OtherEmployeeId,UserName="other@test",Email="other@test",DisplayName="Other Employee"},new ApplicationUser{Id=AgentId,UserName="agent@test",Email="agent@test",DisplayName="Ahmed Hassan"},new ApplicationUser{Id=ManagerId,UserName="manager@test",Email="manager@test",DisplayName="Manager User"});db.UserRoles.Add(new IdentityUserRole<string>{UserId=AgentId,RoleId="role-agent"});db.Tickets.AddRange(new Ticket{Id=1,TicketNumber="HDL-1001",Title="Own ticket",Description="Own",Category="IT Support",Status=TicketStatus.Open,Priority=TicketPriority.Medium,CreatedByUserId=EmployeeId,CreatedAt=DateTimeOffset.UtcNow,UpdatedAt=DateTimeOffset.UtcNow},new Ticket{Id=2,TicketNumber="HDL-1002",Title="Other ticket",Description="Other",Category="Network",Status=TicketStatus.Resolved,Priority=TicketPriority.Low,CreatedByUserId=OtherEmployeeId,AssignedToUserId=AgentId,CreatedAt=DateTimeOffset.UtcNow,UpdatedAt=DateTimeOffset.UtcNow});db.SaveChanges();}
    private void EnsureSeeded(){lock(seedLock){if(seeded)return;using var scope=Services.CreateScope();Seed(scope.ServiceProvider.GetRequiredService<ApplicationDbContext>());seeded=true;}}
    protected override void Dispose(bool disposing){base.Dispose(disposing);if(disposing&&Directory.Exists(AttachmentRoot))Directory.Delete(AttachmentRoot,true);}
}
public sealed class TestAuthHandler(IOptionsMonitor<AuthenticationSchemeOptions> options,ILoggerFactory logger,UrlEncoder encoder):AuthenticationHandler<AuthenticationSchemeOptions>(options,logger,encoder){public const string SchemeName="Test";protected override Task<AuthenticateResult> HandleAuthenticateAsync(){if(!Request.Headers.TryGetValue("X-Test-User",out var id)||!Request.Headers.TryGetValue("X-Test-Role",out var role))return Task.FromResult(AuthenticateResult.NoResult());var claims=new[]{new Claim(ClaimTypes.NameIdentifier,id!),new Claim(ClaimTypes.Name,id!),new Claim(ClaimTypes.Role,role!)};var principal=new ClaimsPrincipal(new ClaimsIdentity(claims,SchemeName));return Task.FromResult(AuthenticateResult.Success(new AuthenticationTicket(principal,SchemeName)));}}
