using System.Net;
using System.Net.Http.Json;
using HelpDeskLite.Api.Contracts;
using HelpDeskLite.Api.Data;
using HelpDeskLite.Api.Domain;
using HelpDeskLite.Api.Services;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc.Testing;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging.Abstractions;

namespace HelpDeskLite.Api.Tests;
public sealed record SentEmail(string Recipient,string Subject,string Html,string Text);
public sealed class FakeEmailService:IEmailService{public List<SentEmail> Messages{get;}=[];public Task SendAsync(string recipient,string subject,string html,string text,CancellationToken cancellationToken=default){Messages.Add(new(recipient,subject,html,text));return Task.CompletedTask;}}
public sealed class AuthApiFactory:WebApplicationFactory<Program>
{
    private readonly string databaseName=$"helpdesk-auth-tests-{Guid.NewGuid():N}";
    protected override IHost CreateHost(IHostBuilder builder){builder.ConfigureServices(services=>{services.RemoveAll<IDataProtectionProvider>();services.AddSingleton<IDataProtectionProvider>(new EphemeralDataProtectionProvider());});return base.CreateHost(builder);}
    protected override void ConfigureWebHost(IWebHostBuilder builder){builder.UseEnvironment("Testing");builder.ConfigureServices(services=>{services.RemoveAll(typeof(DbContextOptions<ApplicationDbContext>));services.RemoveAll(typeof(IDbContextOptionsConfiguration<ApplicationDbContext>));services.AddDbContext<ApplicationDbContext>(options=>options.UseInMemoryDatabase(databaseName));services.RemoveAll<IEmailService>();services.AddSingleton<FakeEmailService>();services.AddSingleton<IEmailService>(provider=>provider.GetRequiredService<FakeEmailService>());});}
    public async Task EnsureRoles(){using var scope=Services.CreateScope();var roles=scope.ServiceProvider.GetRequiredService<RoleManager<IdentityRole>>();foreach(var role in AppRoles.All)if(!await roles.RoleExistsAsync(role))Assert.True((await roles.CreateAsync(new IdentityRole(role))).Succeeded);}
}
public sealed class AuthFlowTests(AuthApiFactory factory):IClassFixture<AuthApiFactory>
{
    private static RegisterRequest Valid(string email)=>new("Omar","Mohamed",email,"StrongTest!123","StrongTest!123");
    private async Task<HttpClient> Client(){await factory.EnsureRoles();return factory.CreateClient(new WebApplicationFactoryClientOptions{HandleCookies=true,BaseAddress=new Uri("https://localhost")});}
    private async Task SeedDemos(AuthApiFactory target){await target.EnsureRoles();using var scope=target.Services.CreateScope();var config=new ConfigurationBuilder().AddInMemoryCollection(new Dictionary<string,string?>{{"SeedUsers:Password","DemoStrong!123"}}).Build();await DevelopmentSeeder.SeedIdentityAsync(scope.ServiceProvider,config,NullLogger.Instance);}
    [Fact]public async Task Registration_creates_unconfirmed_employee_with_names_and_hashed_password(){var email=$"register-{Guid.NewGuid():N}@test.local";var response=await (await Client()).PostAsJsonAsync("/api/auth/register",Valid(email));Assert.Equal(HttpStatusCode.Created,response.StatusCode);using var scope=factory.Services.CreateScope();var manager=scope.ServiceProvider.GetRequiredService<UserManager<ApplicationUser>>();var user=await manager.FindByEmailAsync(email);Assert.NotNull(user);Assert.Equal("Omar",user.FirstName);Assert.Equal("Mohamed",user.LastName);Assert.False(user.EmailConfirmed);Assert.NotEqual("StrongTest!123",user.PasswordHash);Assert.Equal([AppRoles.Employee],await manager.GetRolesAsync(user));var sent=scope.ServiceProvider.GetRequiredService<FakeEmailService>().Messages.Last(x=>x.Recipient==email);Assert.Equal("Confirm your HelpDesk Lite account",sent.Subject);Assert.Contains("Confirm Email",sent.Html);Assert.Contains("Hi Omar,",sent.Html);}
    [Theory][InlineData("","Mohamed","First name is required.")][InlineData("Omar","","Last name is required.")]public async Task Registration_requires_names(string first,string last,string message){var request=Valid($"name-{Guid.NewGuid():N}@test.local") with{FirstName=first,LastName=last};var response=await (await Client()).PostAsJsonAsync("/api/auth/register",request);Assert.Equal(HttpStatusCode.BadRequest,response.StatusCode);Assert.Contains(message,await response.Content.ReadAsStringAsync());}
    [Fact]public async Task Registration_rejects_password_mismatch(){var request=Valid($"mismatch-{Guid.NewGuid():N}@test.local") with{ConfirmPassword="Different!123"};Assert.Equal(HttpStatusCode.BadRequest,(await (await Client()).PostAsJsonAsync("/api/auth/register",request)).StatusCode);}
    [Fact]public async Task Registration_rejects_duplicate_and_privileged_roles(){var email=$"duplicate-{Guid.NewGuid():N}@test.local";var client=await Client();Assert.Equal(HttpStatusCode.Created,(await client.PostAsJsonAsync("/api/auth/register",Valid(email))).StatusCode);Assert.Equal(HttpStatusCode.Conflict,(await client.PostAsJsonAsync("/api/auth/register",Valid(email))).StatusCode);using var scope=factory.Services.CreateScope();var manager=scope.ServiceProvider.GetRequiredService<UserManager<ApplicationUser>>();var roles=await manager.GetRolesAsync((await manager.FindByEmailAsync(email))!);Assert.Equal([AppRoles.Employee],roles);}
    [Fact]public void Registration_and_demo_contracts_cannot_inject_identity(){Assert.DoesNotContain(typeof(RegisterRequest).GetProperties(),p=>p.Name.Equals("Role",StringComparison.OrdinalIgnoreCase));Assert.DoesNotContain(typeof(DemoLoginRequest).GetProperties(),p=>p.Name is "Email" or "Password" or "UserId");}
    [Fact]public async Task Forgot_password_is_enumeration_safe_and_uses_fake_email(){var client=await Client();var unknown=await client.PostAsJsonAsync("/api/auth/forgot-password",new EmailRequest($"unknown-{Guid.NewGuid():N}@test.local"));var email=$"forgot-{Guid.NewGuid():N}@test.local";await client.PostAsJsonAsync("/api/auth/register",Valid(email));using(var scope=factory.Services.CreateScope()){var manager=scope.ServiceProvider.GetRequiredService<UserManager<ApplicationUser>>();var user=(await manager.FindByEmailAsync(email))!;user.EmailConfirmed=true;await manager.UpdateAsync(user);}var known=await client.PostAsJsonAsync("/api/auth/forgot-password",new EmailRequest(email));Assert.Equal(await unknown.Content.ReadAsStringAsync(),await known.Content.ReadAsStringAsync());using var verify=factory.Services.CreateScope();Assert.Contains(verify.ServiceProvider.GetRequiredService<FakeEmailService>().Messages,x=>x.Recipient==email&&x.Subject=="Reset your HelpDesk Lite password"&&x.Html.Contains("Reset Password"));}
    [Fact]public async Task Demo_login_has_strict_role_allowlist(){var response=await (await Client()).PostAsJsonAsync("/api/auth/demo-login",new{role="Admin",email="someone@test.local"});Assert.Equal(HttpStatusCode.BadRequest,response.StatusCode);}
    [Theory][InlineData(AppRoles.Employee,"demo.employee@helpdesklite.local")][InlineData(AppRoles.SupportAgent,"demo.agent@helpdesklite.local")][InlineData(AppRoles.Manager,"demo.manager@helpdesklite.local")]public async Task Seeded_demo_user_has_exact_role_and_can_demo_login(string role,string email){await SeedDemos(factory);using(var scope=factory.Services.CreateScope()){var users=scope.ServiceProvider.GetRequiredService<UserManager<ApplicationUser>>();var user=await users.FindByEmailAsync(email);Assert.NotNull(user);Assert.True(user.EmailConfirmed);Assert.Equal(email.ToUpperInvariant(),user.NormalizedEmail);Assert.Equal([role],await users.GetRolesAsync(user));}var client=await Client();var response=await client.PostAsJsonAsync("/api/auth/demo-login",new DemoLoginRequest(role));Assert.Equal(HttpStatusCode.OK,response.StatusCode);Assert.Contains(response.Headers.GetValues("Set-Cookie"),value=>value.Contains("HelpDeskLite.Auth"));var dto=await response.Content.ReadFromJsonAsync<UserDto>();Assert.True(dto!.IsDemo);Assert.Equal(role,dto.Role);Assert.Equal(HttpStatusCode.OK,(await client.GetAsync("/api/auth/me")).StatusCode);}
    [Fact]public async Task Missing_demo_account_fails_safely(){using var isolated=new AuthApiFactory();await isolated.EnsureRoles();var client=isolated.CreateClient(new WebApplicationFactoryClientOptions{BaseAddress=new Uri("https://localhost")});Assert.Equal(HttpStatusCode.ServiceUnavailable,(await client.PostAsJsonAsync("/api/auth/demo-login",new DemoLoginRequest(AppRoles.Employee))).StatusCode);}
    [Fact]public async Task Wrong_role_demo_account_fails_safely(){using var isolated=new AuthApiFactory();await isolated.EnsureRoles();using(var scope=isolated.Services.CreateScope()){var users=scope.ServiceProvider.GetRequiredService<UserManager<ApplicationUser>>();var user=new ApplicationUser{DisplayName="Wrong Role",UserName="demo.employee@helpdesklite.local",Email="demo.employee@helpdesklite.local",EmailConfirmed=true};Assert.True((await users.CreateAsync(user,"DemoStrong!123")).Succeeded);Assert.True((await users.AddToRoleAsync(user,AppRoles.Manager)).Succeeded);}var client=isolated.CreateClient(new WebApplicationFactoryClientOptions{BaseAddress=new Uri("https://localhost")});Assert.Equal(HttpStatusCode.ServiceUnavailable,(await client.PostAsJsonAsync("/api/auth/demo-login",new DemoLoginRequest(AppRoles.Employee))).StatusCode);}
    [Fact]public async Task Demo_employee_and_manager_keep_real_authorization(){await SeedDemos(factory);var employee=await Client();await employee.PostAsJsonAsync("/api/auth/demo-login",new DemoLoginRequest(AppRoles.Employee));Assert.Equal(HttpStatusCode.Forbidden,(await employee.GetAsync("/api/support/queue")).StatusCode);var manager=await Client();await manager.PostAsJsonAsync("/api/auth/demo-login",new DemoLoginRequest(AppRoles.Manager));Assert.Equal(HttpStatusCode.Forbidden,(await manager.PatchAsJsonAsync("/api/tickets/1/status",new ChangeStatusRequest(TicketStatus.Resolved))).StatusCode);}
    [Fact]public async Task Normal_identity_is_not_demo(){var client=await Client();var email=$"normal-{Guid.NewGuid():N}@test.local";using(var scope=factory.Services.CreateScope()){var users=scope.ServiceProvider.GetRequiredService<UserManager<ApplicationUser>>();var user=new ApplicationUser{DisplayName="Normal User",UserName=email,Email=email,EmailConfirmed=true};Assert.True((await users.CreateAsync(user,"StrongTest!123")).Succeeded);Assert.True((await users.AddToRoleAsync(user,AppRoles.Employee)).Succeeded);}var response=await client.PostAsJsonAsync("/api/auth/login",new LoginRequest(email,"StrongTest!123"));Assert.Equal(HttpStatusCode.OK,response.StatusCode);Assert.False((await response.Content.ReadFromJsonAsync<UserDto>())!.IsDemo);}
}
