import { BrowserRouter, Route, Routes } from 'react-router'
import { AppShell } from './components/layout/AppShell'
import { ProtectedRoute, RoleHome, RoleRoute } from './components/layout/RoleRoute'
import { SessionProvider } from './context/SessionContext'
import { TicketProvider } from './context/TicketContext'
import ConfigurationPreview from './Pages/ConfigurationPreview'
import CreateTicket from './Pages/CreateTicket'
import Login from './Pages/Login'
import ManagerDashboard from './Pages/ManagerDashboard'
import MyTickets from './Pages/MyTickets'
import Settings from './Pages/Settings'
import SupportQueue from './Pages/SupportQueue'
import TicketDetails from './Pages/TicketDetails'
export default function App(){return <BrowserRouter><SessionProvider><TicketProvider><Routes><Route path="/login" element={<Login/>}/><Route element={<ProtectedRoute><AppShell/></ProtectedRoute>}><Route path="/tickets" element={<RoleRoute allow={['Employee']}><MyTickets/></RoleRoute>}/><Route path="/tickets/new" element={<RoleRoute allow={['Employee']}><CreateTicket/></RoleRoute>}/><Route path="/tickets/:ticketId" element={<TicketDetails/>}/><Route path="/support" element={<RoleRoute allow={['Support Agent']}><SupportQueue/></RoleRoute>}/><Route path="/support/all" element={<RoleRoute allow={['Support Agent']}><SupportQueue/></RoleRoute>}/><Route path="/manager" element={<RoleRoute allow={['Manager']}><ManagerDashboard/></RoleRoute>}/><Route path="/settings" element={<Settings/>}/><Route path="/settings/configuration-preview" element={<ConfigurationPreview/>}/></Route><Route path="/" element={<RoleHome/>}/><Route path="*" element={<RoleHome/>}/></Routes></TicketProvider></SessionProvider></BrowserRouter>}
